working pre-commit hook

diff --git a/git/git_template/hooks/pre-commit b/git/git_template/hooks/pre-commit
--- a/git/git_template/hooks/pre-commit
+++ b/git/git_template/hooks/pre-commit
@@ -15,10 +15,10 @@
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ascii filenames set this variable to true.
@@ -31,25 +31,25 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	echo "Error: Attempt to add a non-ascii file name."
-	echo
-	echo "This can cause problems if you want to work"
-	echo "with people on other platforms."
-	echo
-	echo "To be portable it is advisable to rename the file ..."
-	echo
-	echo "If you know what you are doing you can disable this"
-	echo "check using:"
-	echo
-	echo "  git config hooks.allownonascii true"
-	echo
-	exit 1
+    echo "Error: Attempt to add a non-ascii file name."
+    echo
+    echo "This can cause problems if you want to work"
+    echo "with people on other platforms."
+    echo
+    echo "To be portable it is advisable to rename the file ..."
+    echo
+    echo "If you know what you are doing you can disable this"
+    echo "check using:"
+    echo
+    echo "  git config hooks.allownonascii true"
+    echo
+    exit 1
 fi
 
 # Check for source files with no newline at end of file. Note that this
@@ -58,10 +58,10 @@ suffixes=("h" "c" "cc" "cpp" "py" "zsh")
 search=""
 for i in "${suffixes[@]}"
 do
-    search+="\\\\.$i\$"
+    search+="\\.$i\$|"
 done
 
-for file in `git diff --cached --name-only $against| grep -E '$search'`; do
+for file in `git diff --cached --name-only $against| grep -E '${search%?}'`; do
     eof=`tail -c 1 $file`
     if [ "$eof" != "" ]; then
         echo "$file: No newline at the end of file"
